-- Local development seed for Auto Integral
-- Applied automatically by: npx supabase@latest db reset
-- Manual re-seed: npx supabase@latest db reset
--
-- Staff logins (local only):
--   admin@autointegral.local  / AdminLocal123!
--   editor@autointegral.local / EditorLocal123!
--
-- Fictional data only. No real VINs, phones, or provider references.

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Auth users + identities
-- ---------------------------------------------------------------------------

do $$
declare
  admin_id uuid := '11111111-1111-4111-8111-111111111111';
  editor_id uuid := '22222222-2222-4222-8222-222222222222';
begin
  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  )
  values
    (
      '00000000-0000-0000-0000-000000000000',
      admin_id,
      'authenticated',
      'authenticated',
      'admin@autointegral.local',
      crypt('AdminLocal123!', gen_salt('bf')),
      timezone('utc', now()),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"Admin Local","role":"admin"}'::jsonb,
      timezone('utc', now()),
      timezone('utc', now()),
      '',
      '',
      '',
      ''
    ),
    (
      '00000000-0000-0000-0000-000000000000',
      editor_id,
      'authenticated',
      'authenticated',
      'editor@autointegral.local',
      crypt('EditorLocal123!', gen_salt('bf')),
      timezone('utc', now()),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"Editor Local","role":"editor"}'::jsonb,
      timezone('utc', now()),
      timezone('utc', now()),
      '',
      '',
      '',
      ''
    )
  on conflict (id) do nothing;

  insert into auth.identities (
    id,
    user_id,
    identity_data,
    provider,
    provider_id,
    last_sign_in_at,
    created_at,
    updated_at
  )
  values
    (
      admin_id,
      admin_id,
      format('{"sub":"%s","email":"admin@autointegral.local"}', admin_id)::jsonb,
      'email',
      admin_id::text,
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now())
    ),
    (
      editor_id,
      editor_id,
      format('{"sub":"%s","email":"editor@autointegral.local"}', editor_id)::jsonb,
      'email',
      editor_id::text,
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now())
    )
  on conflict do nothing;

  insert into public.admin_profiles (id, email, full_name, role, is_active)
  values
    (admin_id, 'admin@autointegral.local', 'Admin Local', 'admin', true),
    (editor_id, 'editor@autointegral.local', 'Editor Local', 'editor', true)
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role,
    is_active = excluded.is_active;
end $$;

-- ---------------------------------------------------------------------------
-- Sample vehicles (placeholders; no media assets in this phase)
-- ---------------------------------------------------------------------------

insert into public.vehicles (
  id,
  slug,
  category,
  make,
  model,
  version,
  year,
  stock_code,
  body_type,
  mileage_km,
  transmission,
  fuel_type,
  exterior_color,
  public_title,
  short_description,
  full_description,
  price_amount,
  price_label,
  currency,
  status,
  is_published,
  is_featured,
  is_weekly_opportunity,
  opportunity_deadline,
  featured_order,
  damage_summary,
  condition_notes,
  damage_tags,
  public_tags,
  location_label,
  seo_title,
  seo_description,
  published_at,
  created_by,
  updated_by
)
values
  -- Accidentado borrador
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
    'demo-nissan-versa-2018-borrador',
    'accidentado',
    'Nissan',
    'Versa',
    'Sense',
    2018,
    'AI-DRAFT-01',
    'sedan',
    84200,
    'Automática',
    'Gasolina',
    'Plata',
    'Nissan Versa 2018 Sense',
    'Borrador de prueba para panel admin.',
    'Vehículo de demostración en estado borrador. No publicado.',
    null,
    'Solicita información',
    'MXN',
    'draft',
    false,
    false,
    false,
    null,
    null,
    'Golpe frontal leve (demo).',
    'Pendiente de revisión interna.',
    array['defensa_delantera', 'dano_frontal']::text[],
    '{}'::text[],
    'CDMX',
    null,
    null,
    null,
    '11111111-1111-4111-8111-111111111111',
    '11111111-1111-4111-8111-111111111111'
  ),
  -- Recuperado disponible publicado
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
    'demo-toyota-corolla-2020-recuperado',
    'recuperado',
    'Toyota',
    'Corolla',
    'LE',
    2020,
    'AI-REC-02',
    'sedan',
    51200,
    'Automática',
    'Gasolina',
    'Blanco',
    'Toyota Corolla 2020 LE recuperado',
    'Recuperado listo para revisión. Demostración pública.',
    'Unidad recuperada de demostración, publicada en inventario.',
    185000,
    null,
    'MXN',
    'available',
    true,
    true,
    false,
    null,
    2,
    null,
    'Unidad en buen estado general (demo).',
    '{}'::text[],
    array['precio_atractivo', 'recien_publicado']::text[],
    'Área Metropolitana',
    'Toyota Corolla 2020 recuperado',
    'Vehículo recuperado de demostración Auto Integral.',
    timezone('utc', now()) - interval '2 days',
    '11111111-1111-4111-8111-111111111111',
    '22222222-2222-4222-8222-222222222222'
  ),
  -- Seminuevo disponible publicado
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3',
    'demo-mazda-cx5-2021-seminuevo',
    'seminuevo',
    'Mazda',
    'CX-5',
    'i Sport',
    2021,
    'AI-SEMI-03',
    'SUV',
    33800,
    'Automática',
    'Gasolina',
    'Rojo',
    'Mazda CX-5 2021 i Sport',
    'Seminuevo de demostración con bajo kilometraje.',
    'Seminuevo ficticio para pruebas del panel y listados.',
    329000,
    null,
    'MXN',
    'available',
    true,
    false,
    false,
    null,
    null,
    null,
    'Mantenimiento al día (demo).',
    '{}'::text[],
    array['bajo_kilometraje']::text[],
    'CDMX',
    'Mazda CX-5 2021 seminuevo',
    'Seminuevo de demostración Auto Integral.',
    timezone('utc', now()) - interval '1 day',
    '22222222-2222-4222-8222-222222222222',
    '22222222-2222-4222-8222-222222222222'
  ),
  -- Oportunidad activa
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4',
    'demo-honda-civic-2019-oportunidad',
    'accidentado',
    'Honda',
    'Civic',
    'EX',
    2019,
    'AI-OPP-04',
    'sedan',
    67400,
    'Automática',
    'Gasolina',
    'Gris',
    'Honda Civic 2019 EX — oportunidad',
    'Oportunidad activa de demostración para /oportunidades.',
    'Unidad seleccionada para la franja semanal (datos ficticios).',
    155000,
    'Oportunidad de la semana',
    'MXN',
    'available',
    true,
    true,
    true,
    timezone('utc', now()) + interval '5 days',
    1,
    'Daño lateral reparable (demo).',
    'Acompañamiento disponible (demo).',
    array['puerta_izquierda', 'dano_lateral']::text[],
    array['excelente_oportunidad', 'muy_solicitado']::text[],
    'CDMX',
    'Honda Civic oportunidad demo',
    'Oportunidad semanal de demostración.',
    timezone('utc', now()) - interval '12 hours',
    '11111111-1111-4111-8111-111111111111',
    '11111111-1111-4111-8111-111111111111'
  ),
  -- Reservado
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5',
    'demo-vw-jetta-2017-reservado',
    'recuperado',
    'Volkswagen',
    'Jetta',
    'Comfortline',
    2017,
    'AI-RES-05',
    'sedan',
    98000,
    'Manual',
    'Gasolina',
    'Negro',
    'Volkswagen Jetta 2017 reservado',
    'Unidad reservada de demostración.',
    'Reservado para pruebas de acciones admin.',
    129000,
    null,
    'MXN',
    'reserved',
    true,
    false,
    false,
    null,
    null,
    null,
    'Cliente en proceso (demo).',
    '{}'::text[],
    '{}'::text[],
    'Estado de México',
    null,
    null,
    timezone('utc', now()) - interval '3 days',
    '22222222-2222-4222-8222-222222222222',
    '11111111-1111-4111-8111-111111111111'
  ),
  -- Vendido
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6',
    'demo-ford-focus-2016-vendido',
    'seminuevo',
    'Ford',
    'Focus',
    'SE',
    2016,
    'AI-SOLD-06',
    'hatchback',
    110500,
    'Automática',
    'Gasolina',
    'Azul',
    'Ford Focus 2016 SE',
    'Unidad vendida de demostración.',
    'Histórico vendido para filtros y estados.',
    98000,
    null,
    'MXN',
    'sold',
    false,
    false,
    false,
    null,
    null,
    null,
    'Cerrado (demo).',
    '{}'::text[],
    '{}'::text[],
    'CDMX',
    null,
    null,
    null,
    '11111111-1111-4111-8111-111111111111',
    '11111111-1111-4111-8111-111111111111'
  ),
  -- Archivado
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa7',
    'demo-chevrolet-aveo-2015-archivado',
    'accidentado',
    'Chevrolet',
    'Aveo',
    'LS',
    2015,
    'AI-ARCH-07',
    'sedan',
    145000,
    'Manual',
    'Gasolina',
    'Beige',
    'Chevrolet Aveo 2015 LS',
    'Unidad archivada de demostración.',
    'Archivado para pruebas de menú de acciones.',
    null,
    null,
    'MXN',
    'archived',
    false,
    false,
    false,
    null,
    null,
    'Daño estructural (demo).',
    'Fuera de catálogo.',
    array['otro']::text[],
    '{}'::text[],
    'CDMX',
    null,
    null,
    null,
    '22222222-2222-4222-8222-222222222222',
    '22222222-2222-4222-8222-222222222222'
  )
on conflict (id) do nothing;

-- Expired opportunity helper (not active): published opportunity with past deadline
insert into public.vehicles (
  id,
  slug,
  category,
  make,
  model,
  version,
  year,
  stock_code,
  public_title,
  short_description,
  status,
  is_published,
  is_featured,
  is_weekly_opportunity,
  opportunity_deadline,
  published_at,
  created_by,
  updated_by
)
values (
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa8',
  'demo-kia-rio-2018-oportunidad-vencida',
  'recuperado',
  'Kia',
  'Rio',
  'LX',
  2018,
  'AI-EXP-08',
  'Kia Rio 2018 — oportunidad vencida',
  'Oportunidad vencida para pruebas de exclusión.',
  'available',
  true,
  false,
  true,
  timezone('utc', now()) - interval '1 day',
  timezone('utc', now()) - interval '4 days',
  '11111111-1111-4111-8111-111111111111',
  '11111111-1111-4111-8111-111111111111'
)
on conflict (id) do nothing;
